services:
  api:
    build:
      context: ./backend
    restart: always
    ports:
      - "4000:4000"
    networks:
      - frontnet

  frontend:
    build:
      context: ./frontend
    restart: always
    expose:
      - "80"
    # NOTE: deploy.replicas only applies in Swarm mode;
    # for plain Compose use: `docker compose up -d --scale frontend=3`
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - frontnet

  proxy:
    image: nginx:alpine
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
    networks:
      - frontnet

networks:
  frontnet:
